const app=document.getElementById("app"),statusEl=document.getElementById("status");
async function api(path,options={}){const r=await fetch("/api"+path,{headers:{"Content-Type":"application/json"},...options});const d=await r.json();if(!r.ok)throw Error(d.detail||"Erro na API");return d}
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

async function home(){const d=await api("/dashboard");app.innerHTML=`<div class="container"><section class="hero"><p class="muted">A1 • Banco de Dados + Webapp</p><h1>Seu banco virou uma plataforma.</h1><p class="muted">Interface conectada diretamente ao MySQL <b>streaming_db</b>.</p><div class="actions"><button class="primary" onclick="page('catalogo')">Explorar catálogo</button><button onclick="page('admin')">Painel admin</button></div></section><div class="grid">${Object.entries(d).map(([k,v])=>`<div class="card"><div class="muted">${k}</div><div class="metric">${v}</div></div>`).join("")}</div></div>`}

async function catalogo(){const [items,genres]=await Promise.all([api("/conteudos"),api("/generos")]);app.innerHTML=`<div class="container"><h1>Catálogo</h1><p class="muted">Dados reais da tabela conteudo.</p><div class="filters"><select id="tipo"><option value="">Todos</option><option>FILME</option><option>SERIE</option></select><select id="genero"><option value="">Todos os gêneros</option>${genres.map(g=>`<option>${esc(g.nome_genero)}</option>`).join("")}</select><button onclick="filterCatalog()">Filtrar</button></div><div id="catalog" class="grid">${cards(items)}</div></div>`}
function cards(items){return items.length?items.map(c=>`<article class="card"><div class="poster">${esc(c.titulo)}</div><div class="actions"><span class="tag">${c.tipo}</span><span class="tag">${c.ano_lancamento}</span><span class="tag">${c.classificacao_indicativa}</span></div><p class="muted">${esc(c.sinopse||"")}</p><button onclick="details(${c.id_conteudo})">Ver detalhes</button></article>`).join(""):'<div class="empty">Nenhum conteúdo.</div>'}
async function filterCatalog(){const t=document.getElementById("tipo").value,g=document.getElementById("genero").value;document.getElementById("catalog").innerHTML=cards(await api(`/conteudos?tipo=${encodeURIComponent(t)}&genero=${encodeURIComponent(g)}`))}
async function details(id){const c=await api("/conteudos/"+id);const eps=(c.episodios||[]).map(e=>`<div class="episode"><b>T${e.numero_temporada}E${e.numero_episodio} — ${esc(e.titulo_episodio)}</b> <span class="muted">${e.duracao_min} min</span><button style="float:right" onclick="watch(${c.id_conteudo},${e.id_episodio})">Registrar</button></div>`).join("");app.innerHTML=`<div class="container"><button onclick="page('catalogo')">← Catálogo</button><section class="hero"><span class="tag">${c.tipo}</span><h1>${esc(c.titulo)}</h1><p>${esc(c.sinopse||"")}</p><p class="muted">Ano ${c.ano_lancamento} • ${c.classificacao_indicativa} • ${c.duracao_min?c.duracao_min+" min":""}</p></section><h2>Gêneros</h2><p>${esc(c.generos||"")}</p>${c.tipo==="SERIE"?`<h2>Episódios</h2><div class="card">${eps}</div>`:`<button class="primary" onclick="watch(${c.id_conteudo},null)">Registrar visualização</button>`}</div>`}
async function watch(id,episode){const ps=await api("/perfis");const p=prompt("ID do perfil:\n"+ps.map(x=>`${x.id_perfil} - ${x.usuario} / ${x.nome_perfil}`).join("\n"));if(!p)return;try{await api("/historico",{method:"POST",body:JSON.stringify({id_perfil:Number(p),id_conteudo:id,id_episodio:episode,tempo_assistido_min:0,concluido:false})});alert("Visualização registrada no MySQL!")}catch(e){alert(e.message)}}
async function historico(){const h=await api("/historico");app.innerHTML=`<div class="container"><h1>Histórico</h1><p class="muted">JOIN entre usuário, perfil, conteúdo e episódio.</p><div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Perfil</th><th>Conteúdo</th><th>Episódio</th><th>Data</th><th>Tempo</th><th>Status</th></tr></thead><tbody>${h.map(x=>`<tr><td>${esc(x.usuario)}</td><td>${esc(x.nome_perfil)}</td><td>${esc(x.titulo)}</td><td>${x.titulo_episodio?`T${x.numero_temporada}E${x.numero_episodio} - ${esc(x.titulo_episodio)}`:"Filme"}</td><td>${esc(x.data_hora_inicio)}</td><td>${x.tempo_assistido_min} min</td><td>${x.concluido?"✓ concluído":"Em andamento"}</td></tr>`).join("")}</tbody></table></div></div>`}
async function admin(){const [u,a,r,p]=await Promise.all([api("/usuarios"),api("/assinaturas"),api("/receita"),api("/planos")]);app.innerHTML=`<div class="container"><h1>Painel administrativo</h1><div class="grid"><div class="card"><div class="muted">Usuários</div><div class="metric">${u.length}</div></div><div class="card"><div class="muted">Assinaturas</div><div class="metric">${a.length}</div></div><div class="card"><div class="muted">Receita ativa</div><div class="metric">${money(r.reduce((s,x)=>s+Number(x.receita_mensal||0),0))}</div></div></div><h2>Planos</h2><div class="grid">${p.map(x=>`<div class="card"><b>${esc(x.nome_plano)}</b><div class="metric">${money(x.preco_mensal)}</div><p class="muted">${x.qualidade_maxima} • ${x.telas_simultaneas} tela(s)<br>${x.permite_download?"✓ Download":"✗ Download"}</p></div>`).join("")}</div><h2>Assinaturas</h2><div class="table-wrap"><table><thead><tr><th>Usuário</th><th>Plano</th><th>Preço</th><th>Status</th><th>Pagamento</th></tr></thead><tbody>${a.map(x=>`<tr><td>${esc(x.usuario)}</td><td>${esc(x.nome_plano)}</td><td>${money(x.preco_mensal)}</td><td>${x.status}</td><td>${x.forma_pagamento}</td></tr>`).join("")}</tbody></table></div><h2>Usuários</h2><button class="primary" onclick="newUser()">+ Novo usuário</button><div class="table-wrap" style="margin-top:15px"><table><thead><tr><th>ID</th><th>Nome</th><th>E-mail</th><th>País</th></tr></thead><tbody>${u.map(x=>`<tr><td>${x.id_usuario}</td><td>${esc(x.nome)}</td><td>${esc(x.email)}</td><td>${esc(x.pais)}</td></tr>`).join("")}</tbody></table></div></div>`}
async function newUser(){const nome=prompt("Nome:");if(!nome)return;const email=prompt("E-mail:");if(!email)return;const nasc=prompt("Nascimento (AAAA-MM-DD):","2000-01-01");if(!nasc)return;const pais=prompt("País:","BR");try{await api("/usuarios",{method:"POST",body:JSON.stringify({nome,email,data_nascimento:nasc,pais})});alert("Usuário criado no MySQL!");admin()}catch(e){alert(e.message)}}
function page(p){({home,catalogo,historico,admin}[p]||home)()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>page(b.dataset.page));
(async()=>{try{await api("/health");statusEl.textContent="● banco conectado";statusEl.style.color="#86efac"}catch(e){statusEl.textContent="● banco offline";statusEl.style.color="#f87171"}home()})();
